# # 本番環境のDBに対してマイグレーションを実行する。GitHub Actionsで手動実行する

name: Migrate Database Prod to Cloudflare D1
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Migrate D1 Database with Wrangler (Prod)
    runs-on: ubuntu-latest
    env:
      NO_D1_WARNING: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install Deps
        run: bun install
      - name: Run Migration
        run: bun run wrangler d1 migrations apply qwikcity-db --remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        working-directory: .
